extends: [eslint:recommended]
root: true
rules:
  eol-last: error
  eqeqeq: [error, allow-null]
  indent: [error, 2, { SwitchCase: 2 }]
  no-trailing-spaces: error
  no-unused-vars: [error, { vars: all, args: all, ignoreRestSiblings: true, argsIgnorePattern: "^_" }]
  spaced-comment: [error, always]
  semi: [error, always]
parserOptions:
  ecmaVersion: 2019
  sourceType: module
env:
  node: true
  es2017: true
  jest: true
